name: Kotlin CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build shadowJar
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew shadowJar
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          registry: registry.nush.app
          repository: appventure-bot
          tags: latest
          push: false
