name: Kotlin CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build shadowJar
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew shadowJar
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app
          repository: appventure-bot
          tags: latest
